"""Public M01 surface API; preview dependencies are deliberately not imported here."""

from .contracts import (
    BoundaryMode,
    CapabilityManifest,
    ClosestFeature,
    ConvergenceLevel,
    Domain2D,
    DomainStatus,
    FieldQueryResult,
    LatentNoiseIdentity,
    M01ReasonCode,
    QualityStatus,
    QueryCapability,
    QueryFootprint,
    QueryResponse,
    RoughnessTier,
    SurfaceCreationResult,
    SurfaceFamily,
    SurfaceRealization,
    SurfaceSourceDescriptor,
    SurfaceSourceKind,
    SurfaceSpec,
    TrustedScaleBand,
    VisualizationSample,
    make_latent_noise_identity,
    make_visualization_sample,
)
from .materialization import (
    ContentAddressedTileCache,
    FootprintGuard,
    LODLevel,
    MaterializationConfig,
    TileMaterializer,
    derive_query_footprint,
    sample_visualization_window,
)
from .mesh_regression import heightfield_triangulation_regression_adapter
from .provider import (
    SurfaceProvider,
    SurfaceQueryHandle,
    make_analytic_source_descriptor,
    make_measured_source_descriptor,
    make_synthetic_source_descriptor,
    validate_source_descriptor,
)
from .query import (
    SurfaceQuery,
    query_closest_features,
    query_height_differential,
    query_neighborhood,
    query_signed_distance,
)
from .result_extension import surface_result_extension
from .sphere import (
    generic_sphere_clearance,
    height_field_spherical_envelope,
    query_spherical_envelope_or_clearance,
    validate_sphere_path_consistency,
)
from .synthetic import SyntheticEvaluator, synthetic_parameters_for_tier

__all__ = [
    "BoundaryMode",
    "CapabilityManifest",
    "ClosestFeature",
    "ContentAddressedTileCache",
    "ConvergenceLevel",
    "Domain2D",
    "DomainStatus",
    "FieldQueryResult",
    "FootprintGuard",
    "LODLevel",
    "LatentNoiseIdentity",
    "M01ReasonCode",
    "MaterializationConfig",
    "QualityStatus",
    "QueryCapability",
    "QueryFootprint",
    "QueryResponse",
    "RoughnessTier",
    "SurfaceCreationResult",
    "SurfaceFamily",
    "SurfaceProvider",
    "SurfaceQuery",
    "SurfaceQueryHandle",
    "SurfaceRealization",
    "SurfaceSourceDescriptor",
    "SurfaceSourceKind",
    "SurfaceSpec",
    "SyntheticEvaluator",
    "TileMaterializer",
    "TrustedScaleBand",
    "VisualizationSample",
    "derive_query_footprint",
    "generic_sphere_clearance",
    "height_field_spherical_envelope",
    "heightfield_triangulation_regression_adapter",
    "make_analytic_source_descriptor",
    "make_latent_noise_identity",
    "make_measured_source_descriptor",
    "make_synthetic_source_descriptor",
    "make_visualization_sample",
    "query_closest_features",
    "query_height_differential",
    "query_neighborhood",
    "query_signed_distance",
    "query_spherical_envelope_or_clearance",
    "sample_visualization_window",
    "surface_result_extension",
    "synthetic_parameters_for_tier",
    "validate_source_descriptor",
    "validate_sphere_path_consistency",
]
